# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: imagexample.proto for package 'imagexample'

require 'grpc'
require 'imagexample_pb'

module Imagexample
  module ImageCaptchaService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'imagexample.ImageCaptchaService'

      rpc :ResolveCaptcha, ImageRequest, ImageResponse
    end

    Stub = Service.rpc_stub_class
  end
end
